# Generated by Django 6.0.5 on 2026-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agroapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
