# Generated by Django 6.0.5 on 2026-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agroapp', '0002_remove_farmerprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farming_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='farmer_documents/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='main_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_profiles/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
