# Generated by Django 6.0.4 on 2026-05-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agroapp', '0003_rename_location_farmerprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='city',
        ),
    ]
