# Generated by Django 6.0.4 on 2026-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agroapp', '0012_remove_customer_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
